import type {Metadata} from 'next';
import Header from '@/components/Header';
import {Open_Sans} from 'next/font/google';
import NavBar from '@/components/NavBar';
import MainLayout from '@/components/MainLayout';
import {DashboardProvider} from '@/context/DashboardContext';
import {navBarData} from '@/mockData';
import './globals.css';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Kanut',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${openSans.variable}`}>
        <DashboardProvider>
          <Header title={metadata.title} />
          <NavBar navBarData={navBarData} />
          <MainLayout>{children}</MainLayout>
        </DashboardProvider>
      </body>
    </html>
  );
}
